# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6157c9c39927b6b86360bf0ef92b5b0755ef553ef295be12bde8cdf479ee34fe7b62c045c28c45e3559aa8045beffe67e41bee301c148dd9cc8c182e7c96b51f

test:
  secret_key_base: 0a92c655df960aae0b6bf0decb6a001aff27eec047171eb6499a5fbbaf754e87044afd9f2f46c16298b7e702b8de83716157514bb4e8989baaa124b03e2057b0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
